version: '3.8'

services:
  # Build the app services
  app:
    build: app
    ports:
      - 5001-5003:5000
  nginx:
    container_name: nginx
    build: nginx
    # Bind the port 80 of container to machine port 9090
    ports:
      - 9090:80
    # Make app as nginx dependency service
    depends_on:
      - app
